server:
  port: 8080

zk:
  # Заглавная страница приложения, на которую будет выполняться вход
  # при открытии адреса host:${server.port}/${server.servlet.context-path},
  # если не указывать дальнейший путь
  # Матчится по дефолтному имени директории с zul-файлами в Springboot и .zul-суффиксу имени файла
#  homepage: main
  # Включение / выключение использования вэбсокетов. На текущий момент не используется приложением,
  # однако по умполчанию включено и вызывает ошибки при старте из-за ненужных зависимостей
  websockets-enabled: false
  # Путь к сервлету для UpdateEngine ZK, "rarely used",
  # однако необходим для маршрутизации к zul-файлам (см. javadoc к zk.zul-view-redirect-path)
  update-uri: /zkau
  # Относительный путь для выполнения редиректа на main / index страницы при работе приложения.
  # Кастомная настройка, см. javadoc
  zul-view-redirect-path: ${zk.update-uri}/web
